### ISSUE TITLE
E926 API Support

### ISSUE THREAD

**Issue by kurohai** [tjg1/nori#55]
#53 E926 is the SFW version of E621. They use the same API. The API detection seems to only check the URL. I tried the https://e926.net URL, with no luck. Other than adding this as a supported URL, could the API detection try all versions of the APIs for any unknown URL?

**Comment by tjg1** [comment]
The E621 client code wasn't written by me, and I wasn't aware of E926's existence, because I'm not into *that kinda stuff* (no judging).

There is [an automatic check](https://github.com/tjg1/norilib/blob/d25b26e40b6a2b5ba45bde2b243d6532c97074fe/src/main/java/io/github/tjg1/library/norilib/service/ServiceTypeDetectionService.java#L83), which checks for the existence (200 HTTP response) of URL endpoints for each API type.

- `/posts.xml` for Danbooru 2.0
- `/post/index.xml` for Danbooru Legacy
- `/index.php?page=dapi&s=post&q=index` for Gelbooru
- `/api/danbooru/find_posts/index.xml` for Shimmie

The problem with the E621/E926 API is that it uses the `/post/index.xml` endpoint (Danbooru Legacy) with an API that is loosely based on Danbooru 2.0, with some XML tags named differently - e.g. `<created_at>` vs `<created-at>`. 

That's why the value was hardcoded.
